[metadata]
name = scnet
version = 0.1.0
description = SCNet music source separation model
author = StarryTong
license = MIT
long_description = file: README.md
long_description_content_type = text/markdown

[options]
packages = find:
python_requires = >=3.10
include_package_data = True
install_requires =
    accelerate==0.32.1
    julius==0.2.7
    ml_collections==0.1.1
    numpy
    PyYAML
    soundfile==0.12.1
    torch==2.9.0
    torchaudio==2.9.0
    tqdm
    einops==0.6.1
